apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-dev
  namespace: argocd
spec:
  destination:
    namespace: helmapps
    server: 'https://kubernetes.default.svc'
  project: default
  sources:
  # Chart from Chart Repo
  - chart: hello
    repoURL: https://cloudecho.github.io/charts/
    targetRevision: 0.1.0
    helm:
      # https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
      valueFiles:
      - $values/multiple-source-application/values-dev.yaml
  # Values from Git
  - repoURL: 'https://github.com/edco29/argo-cd-helm-values-demo.git'
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
